language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.5
  - 3.6

env:
  global:
    # List package dependencies for conda
    - CONDA_FORGE_DEPS="pytest numpy scipy h5py"
    # Path to the tests
    - TESTS_DIR="unit_tests"

install:
# download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install -c conda-forge $CONDA_FORGE_DEPS
- pip install pytest-ordering scanpy
- pip install git+https://github.com/jacoblevine/phenograph.git

script:
- pytest $TESTS_DIR

notifications:
  email: false
